name: Prettier format

on:
 workflow_dispatch:

jobs:
 check:
  name: Format code
  runs-on: ubuntu-latest
  strategy:
   fail-fast: false
   matrix:
    language: ["javascript"]
    node: ["16.x"]
  steps:
   - name: ğŸ§± Checkout repository
     uses: actions/checkout@v3
   - name: ğŸ”© Setup Node
     uses: actions/setup-node@v3
     with:
      node-version: 16
      cache: "npm"
   - name: ğŸš€ Install dependencies
     run: npm ci --legacy-peer-deps
   - name: "ğŸš€ Format code"
     run: "npm run format"
   - name: "ğŸš€ Commit formatted code"
     uses: stefanzweifel/git-auto-commit-action@v4
     with:
      commit_message: "[ğŸš€] Code formatting"
      branch: ${{ github.head_ref }}
