name: Prettier format

on:
 workflow_dispatch:

jobs:
 check:
  name: Format code
  runs-on: ubuntu-latest
  strategy:
   fail-fast: false
   matrix:
    language: ["javascript"]
    node: ["16.x"]
  steps:
   - name: ğŸ§± Checkout repository
     uses: actions/checkout@v3
   - name: ğŸ”© Setup PNPM
     uses: pnpm/action-setup@v2
     with:
      version: 7
   - name: ğŸ”© Setup Node ${{ matrix.node }}
     uses: actions/setup-node@v3
     with:
      node-version: ${{ matrix.node }}
      cache: "pnpm"
   - name: ğŸš€ Install dependencies
     run: pnpm install
   - name: "ğŸš€ Format code"
     run: "pnpm run format"
   - name: "ğŸš€ Commit formatted code"
     uses: stefanzweifel/git-auto-commit-action@v4
     with:
      commit_message: "[ğŸš€] Code formatting"
      branch: ${{ github.head_ref }}
